"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import macholib_patch
import sys
site_packages = [path for path in sys.path if path.rstrip("/\\").endswith('site-packages')]
print(site_packages)


from setuptools import setup

APP = ['KnitEditor.py']
DATA_FILES = site_packages
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
